Repository ajmaln-tw/react-vuln-scanner, pull requests merged in 2023-10, with the labels that each got.

#1 cli added
  LICENSE
  README.md
  cli.js
  package.json
Labels: hackoctober-accpted, web-security, react-security

#2 added console.log for scanner
  src/scanner.js
Labels: hacktoberfest-accepted, web-security, react-security

#3 added typescript support
  README.md
  package.json
Labels: hacktoberfest-accepted, web-security, react-security

#4 repo added
  package.json
Labels: hacktoberfest-accepted

#5 printing same line
  src/scanner.js
Labels: hacktoberfest-accepted

#6 Succes message when completed
  README.md
  cli.js
  package.json
  src/scanner.js
Labels: hacktoberfest-accepted
